---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perumal-app
  labels:
    app: perumal-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perumal-app
  template:
    metadata:
      labels:
        app: perumal-app
    spec:
      containers:
      - name: perumal-container
        image: 519852036875.dkr.ecr.us-east-2.amazonaws.com/amazon-prime:latest
        ports:
        - containerPort: 3000
...
